# Generated by Django 4.0 on 2023-03-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
