# Generated by Django 4.0 on 2023-03-23 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='signin',
        ),
    ]
